# setup_r_env
source("~/git/Kevin_R_scripts/import_data.r")
source("~/git/Kevin_R_scripts/export_data.r")
source("~/git/Kevin_R_scripts/import_metadata.r")
source("~/git/Kevin_R_scripts/preprocessing_tool.r")
source("~/git/Kevin_R_scripts/calculate_pco.r")
source("~/git/Kevin_R_scripts/render_calculated_pcoa.r")
source("~/git/Kevin_R_scripts/heatmap_dendrogram.r")
source("~/git/Kevin_R_scripts/calc_stats.r")
source("~/git/Kevin_R_scripts/stats_2_data.r")
